resolver: nightly-2021-11-28

packages:
  - co-log-core
  - co-log
  - co-log-polysemy
  - co-log-benchmark

extra-deps:
  - chronos-1.1.3
  - bytebuild-0.3.9.0
  - byteslice-0.2.6.0
  - bytesmith-0.3.8.0
  - contiguous-0.6.1
  - primitive-unlifted-0.1.3.1
  - run-st-0.1.1.0
